return {
  {
    'folke/lazydev.nvim',
    ft = 'lua',
    opts = {
      library = {
        -- Load luvit types when the `vim.uv` word is found
        { path = 'luvit-meta/library', words = { 'vim%.uv' } },
      },
    },
  },
  { 'Bilal2453/luvit-meta', lazy = true },
  {
    -- Main LSP Configuration
    'neovim/nvim-lspconfig',
    dependencies = {
      { 'williamboman/mason.nvim', config = true }, -- NOTE: Must be loaded before dependants
      'williamboman/mason-lspconfig.nvim',
      'WhoIsSethDaniel/mason-tool-installer.nvim',
      { 'j-hui/fidget.nvim', opts = {} },
      'hrsh7th/cmp-nvim-lsp',
    },
    config = function()
      vim.api.nvim_create_autocmd('LspAttach', {
        group = vim.api.nvim_create_augroup('kickstart-lsp-attach', { clear = true }),
        callback = function(event)
          local map = function(keys, func, desc, mode)
            mode = mode or 'n'
            vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = 'LSP: ' .. desc })
          end

          map('gd', require('telescope.builtin').lsp_definitions, '[G]oto [D]efinition')
          map('gr', require('telescope.builtin').lsp_references, '[G]oto [R]eferences')
          map('gI', require('telescope.builtin').lsp_implementations, '[G]oto [I]mplementation')
          map('<leader>D', require('telescope.builtin').lsp_type_definitions, 'Type [D]efinition')
          map('<leader>ds', require('telescope.builtin').lsp_document_symbols, '[D]ocument [S]ymbols')
          map('<leader>ws', require('telescope.builtin').lsp_dynamic_workspace_symbols, '[W]orkspace [S]ymbols')
          map('<leader>rn', vim.lsp.buf.rename, '[R]e[n]ame')
          map('<leader>ca', vim.lsp.buf.code_action, '[C]ode [A]ction', { 'n', 'x' })
          map('gD', vim.lsp.buf.declaration, '[G]oto [D]eclaration')
          -- will be useful to look at definition in a preview [good thing is hover goes away only on moving mouse and not like pressing Esc]
          map('<leader>ph', vim.lsp.buf.hover, 'LS[P] [H]over')

          local client = vim.lsp.get_client_by_id(event.data.client_id)
          if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_inlayHint) then
            map('<leader>th', function()
              vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled { bufnr = event.buf })
            end, '[T]oggle Inlay [H]ints')
          end
        end,
      })

      local capabilities = vim.lsp.protocol.make_client_capabilities()
      capabilities = vim.tbl_deep_extend('force', capabilities, require('cmp_nvim_lsp').default_capabilities())

      -- gopls is configured here via the native vim.lsp.config() API (Neovim 0.11) rather than
      -- through the `servers` table below. Reason: nvim 0.11 + mason-lspconfig v2 dropped the old
      -- lspconfig `handlers` mechanism, so any per-server opts in that table are silently ignored.
      -- Configuring gopls natively also lets us pin our self-built gopls (v0.22.0, go1.26) instead
      -- of Mason's stale v0.16.2 — Mason prepends its bin dir to PATH, so a bare `gopls` would
      -- resolve to the old Nov-2024 copy. lspconfig's lsp/gopls.lua supplies the base
      -- cmd/filetypes/root_dir; we override cmd + capabilities + settings on top of it.
      vim.lsp.config('gopls', {
        cmd = { vim.fn.expand '~/go/bin/gopls' },
        capabilities = capabilities,
        settings = {
          gopls = {
            -- Exclude generated/build artefact dirs from file watching (speeds up large monorepos)
            directoryFilters = { '-.git', '-.bazel', '-bazel-bin', '-bazel-out', '-vendor' },
            analyses = {
              unusedparams = true,
              shadow = false,
            },
            staticcheck = false, -- disable to reduce CPU on large monorepos
            gofumpt = false,
            usePlaceholders = true,
            completeUnimported = true,
            -- This is a Bazel monorepo: proto .pb.go files are generated by Bazel at build time
            -- and not committed. The standard `go list` driver fails because those packages have
            -- no .go files on disk. GOPACKAGESDRIVER tells gopls to use the Bazel-aware driver
            -- (built from @io_bazel_rules_go//go/tools/gopackagesdriver) which queries Bazel for
            -- package metadata instead. The driver gracefully falls back outside Bazel workspaces.
            env = vim.tbl_extend('force', {
              GOPRIVATE = 'eng-hs-gitlab.juniper.net',
              GONOSUMDB = 'eng-hs-gitlab.juniper.net',
              GONOPROXY = 'eng-hs-gitlab.juniper.net',
            }, vim.uv.os_uname().sysname == 'Darwin' and {
              -- Bazel-aware packages driver; needed on macOS where `go list` fails for
              -- proto-generated packages not committed to the repo. Not required on Linux.
              GOPACKAGESDRIVER = vim.fn.expand '~/go/bin/gopackagesdriver-wrapper',
            } or {}),
          },
        },
      })
      vim.lsp.enable 'gopls'

      local servers = {
        pyright = {
          settings = {
            python = {
              venvPath = '/Users/nagakiran/.pyenv/versions',
              venv = 'myenv',
            },
          },
        },
        eslint = {},
        ts_ls = {
          -- Native (nvim 0.11) root_dir signature: (bufnr, on_dir). Prefer the git root
          -- (single tsserver across the monorepo), else nearest tsconfig/package.json.
          root_dir = function(bufnr, on_dir)
            local fname = vim.api.nvim_buf_get_name(bufnr)
            local dir = vim.fs.root(fname, '.git') or vim.fs.root(fname, { 'tsconfig.json', 'package.json' })
            on_dir(dir or vim.fs.dirname(fname))
          end,
          init_options = {
            -- Need to use when specific tsconfig to be chosen like atom/stockscreener
            -- tsconfig = vim.fn.getcwd() .. '/tsconfig.json',
          },
        },
        jdtls = {
          cmd = function(config)
            local root = config.root_dir or vim.uv.cwd()
            local workspace = vim.fn.expand '~/.cache/jdtls/workspace/' .. root:gsub('[/\\]', '_')
            return {
              'jdtls',
              '-configuration',
              vim.fn.expand '~/.cache/jdtls/config',
              '-data',
              workspace,
            }
          end,
          root_dir = function(bufnr, on_dir)
            local fname = vim.api.nvim_buf_get_name(bufnr)
            on_dir(vim.fs.root(fname, '.classpath') or vim.fs.root(fname, '.git') or vim.uv.os_homedir())
          end,
        },
        lua_ls = {
          settings = {
            Lua = {
              completion = {
                callSnippet = 'Replace',
              },
            },
          },
        },
      }

      -- nvim 0.11 + mason-lspconfig v2 dropped the `handlers` callback API: it auto-enables
      -- installed servers via vim.lsp.enable() and reads each server's config from
      -- vim.lsp.config[name]. So register capabilities globally ('*' merges into every server)
      -- and push each server's overrides through the native vim.lsp.config(). (gopls is
      -- configured + enabled separately above so we can pin its binary.)
      vim.lsp.config('*', { capabilities = capabilities })
      for name, cfg in pairs(servers) do
        vim.lsp.config(name, cfg)
      end

      require('mason').setup()

      local ensure_installed = vim.tbl_keys(servers or {})
      vim.list_extend(ensure_installed, {
        'stylua',
      })
      require('mason-tool-installer').setup { ensure_installed = ensure_installed }

      -- Auto-installs + auto-enables the servers in `ensure_installed` using the configs
      -- registered above via vim.lsp.config.
      require('mason-lspconfig').setup {}
    end,
  },
}
